<a href="https://colab.research.google.com/github/vtminc1000/Analisis-Sentimen-SVM-TF-IDF/blob/main/01_scraping_youtube_nuklir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Project Analisis Sentimen Nuklir")

Project Analisis Sentimen Nuklir

In [ ]:
!pip install google-api-python-client pandas

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.194.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.3.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.27.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.4.22)

In [ ]:
from googleapiclient.discovery import build
import pandas as pd
import time

In [ ]:
API_KEY = "AIzaSyAkogVbTY_Am_19yWdY8bX2YNWRAeLOlr4"

In [ ]:
video_id = "DWKoP0eIqq0"

In [ ]:
youtube = build("youtube", "v3", developerKey=API_KEY)

comments = []
next_page_token = None

while True:
    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        maxResults=100,
        pageToken=next_page_token,
        textFormat="plainText"
    )

    response = request.execute()

    for item in response["items"]:
        comment = item["snippet"]["topLevelComment"]["snippet"]

        comments.append({
            "platform": "youtube",
            "video_id": video_id,
            "author": comment.get("authorDisplayName"),
            "text": comment.get("textDisplay"),
            "like_count": comment.get("likeCount"),
            "published_at": comment.get("publishedAt")
        })

    next_page_token = response.get("nextPageToken")

    if next_page_token is None:
        break

    time.sleep(0.5)

df = pd.DataFrame(comments)

print("Jumlah komentar:", len(df))
df.head()

Jumlah komentar: 397

,platform,video_id,author,text,like_count,published_at
0,youtube,DWKoP0eIqq0,@hamidasukmasari2566,Kemenkes RI,0,2026-04-27T08:56:27Z
1,youtube,DWKoP0eIqq0,@MuhamadAndriek,Perbanyak bikin rudal buat perang badar nanti 😂,0,2026-02-28T22:59:01Z
2,youtube,DWKoP0eIqq0,@FikiIlham-e2y,"Mantap ,kpn akn di laksanakan",1,2026-02-27T22:51:36Z
3,youtube,DWKoP0eIqq0,@pinjal80,Ayo gaskan . Jgn mau ditakut takuti antek bara...,0,2026-02-27T14:40:58Z
4,youtube,DWKoP0eIqq0,@muhamadfikiilham3633,gass teruss,0,2026-02-27T13:09:01Z

In [ ]:
df.to_csv("komentar_youtube_nuklir.csv", index=False, encoding="utf-8-sig")

In [ ]:
from google.colab import files
files.download("komentar_youtube_nuklir.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("komentar_youtube_nuklir.csv")

df.head()

,platform,video_id,author,text,like_count,published_at
0,youtube,DWKoP0eIqq0,@hamidasukmasari2566,Kemenkes RI,0,2026-04-27T08:56:27Z
1,youtube,DWKoP0eIqq0,@MuhamadAndriek,Perbanyak bikin rudal buat perang badar nanti 😂,0,2026-02-28T22:59:01Z
2,youtube,DWKoP0eIqq0,@FikiIlham-e2y,"Mantap ,kpn akn di laksanakan",1,2026-02-27T22:51:36Z
3,youtube,DWKoP0eIqq0,@pinjal80,Ayo gaskan . Jgn mau ditakut takuti antek bara...,0,2026-02-27T14:40:58Z
4,youtube,DWKoP0eIqq0,@muhamadfikiilham3633,gass teruss,0,2026-02-27T13:09:01Z

In [ ]:
df.columns

Index(['platform', 'video_id', 'author', 'text', 'like_count', 'published_at'], dtype='object')

In [ ]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.0 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
import re
import string

In [ ]:
def clean_text(text):

    # lowercase
    text = text.lower()

    # hapus URL
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # hapus mention dan hashtag
    text = re.sub(r'@\w+|#\w+', '', text)

    # hapus angka
    text = re.sub(r'\d+', '', text)

    # hapus tanda baca
    text = text.translate(str.maketrans('', '', string.punctuation))

    # hapus spasi berlebih
    text = text.strip()

    return text

In [ ]:
df["clean_text"] = df["text"].astype(str).apply(clean_text)

In [ ]:
df[["text", "clean_text"]].head(10)

,text,clean_text
0,Kemenkes RI,kemenkes ri
1,Perbanyak bikin rudal buat perang badar nanti 😂,perbanyak bikin rudal buat perang badar nanti 😂
2,"Mantap ,kpn akn di laksanakan",mantap kpn akn di laksanakan
3,Ayo gaskan . Jgn mau ditakut takuti antek bara...,ayo gaskan jgn mau ditakut takuti antek barat...
4,gass teruss,gass teruss
5,Jika indonesia bangun nuklir jangan terkoneksi...,jika indonesia bangun nuklir jangan terkoneksi...
6,Mantappppp,mantappppp
7,Kita lihat apakah ambisi atau omongan nya yg b...,kita lihat apakah ambisi atau omongan nya yg b...
8,mantap pk prabowo,mantap pk prabowo
9,😂😂😂😂😂,😂😂😂😂😂

In [ ]:
df = df[df["clean_text"] != ""]

In [ ]:
df = df.drop_duplicates(subset="clean_text")

In [ ]:
print("Jumlah data setelah cleaning:", len(df))

Jumlah data setelah cleaning: 395

In [ ]:
df.to_csv("komentar_youtube_nuklir_clean.csv", index=False, encoding="utf-8-sig")

In [ ]:
from google.colab import files
files.download("komentar_youtube_nuklir_clean.csv")

In [ ]:
!pip install Sastrawi nltk

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords
import nltk

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

stop_words = set(stopwords.words('indonesian'))

In [ ]:
def preprocess_text(text):

    # stemming
    text = stemmer.stem(text)

    # stopword removal
    words = text.split()

    filtered_words = [
        word for word in words
        if word not in stop_words
    ]

    text = " ".join(filtered_words)

    return text

In [ ]:
df["processed_text"] = df["clean_text"].apply(preprocess_text)

In [ ]:
df[["clean_text", "processed_text"]].head(10)

,clean_text,processed_text
0,kemenkes ri,kemenkes ri
1,perbanyak bikin rudal buat perang badar nanti 😂,bikin rudal perang badar
2,mantap kpn akn di laksanakan,mantap kpn akn laksana
3,ayo gaskan jgn mau ditakut takuti antek barat...,ayo gas jgn takut takut antek barat nuklir bah...
4,gass teruss,gass teruss
5,jika indonesia bangun nuklir jangan terkoneksi...,indonesia bangun nuklir koneksi dng jaring int...
6,mantappppp,mantappppp
7,kita lihat apakah ambisi atau omongan nya yg b...,lihat ambisi omong nya yg jgn kau korban masya...
8,mantap pk prabowo,mantap pk prabowo
9,😂😂😂😂😂,

In [ ]:
df = df[df["processed_text"] != ""]

In [ ]:
df.to_csv("komentar_youtube_nuklir_processed.csv", index=False, encoding="utf-8-sig")

In [ ]:
from google.colab import files
files.download("komentar_youtube_nuklir_processed.csv")

In [ ]:
label_df = df[["processed_text"]].copy()

label_df.head()

                                      processed_text
0                                        kemenkes ri
1                           bikin rudal perang badar
2                             mantap kpn akn laksana
3  ayo gas jgn takut takut antek barat nuklir bah...
4                                        gass teruss

In [ ]:
label_df["label"] = ""

label_df.head()

                                      processed_text label
0                                        kemenkes ri
1                           bikin rudal perang badar
2                             mantap kpn akn laksana
3  ayo gas jgn takut takut antek barat nuklir bah...
4                                        gass teruss

In [ ]:
label_df.to_csv("labeling_sentimen.csv", index=False, encoding="utf-8-sig")

In [ ]:
from google.colab import files
files.download("labeling_sentimen.csv")