<a href="https://colab.research.google.com/github/vtminc1000/Analisis-Sentimen-SVM-TF-IDF/blob/main/03_labeling_sentimen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("komentar_youtube_nuklir_clean.csv")

df.head()

,text,clean_text
0,Kemenkes RI,kemenkes ri
1,Perbanyak bikin rudal buat perang badar nanti 😂,perbanyak bikin rudal buat perang badar nanti
2,"Mantap ,kpn akn di laksanakan",mantap kpn akn di laksanakan
3,Ayo gaskan . Jgn mau ditakut takuti antek bara...,ayo gaskan jgn mau ditakut takuti antek barat ...
4,gass teruss,gass teruss

In [ ]:
sample_label = df.sample(n=300, random_state=42)

sample_label = sample_label[["text", "clean_text"]].copy()
sample_label["label"] = ""

sample_label.head()

,text,clean_text,label
336,Amerika siap 2 Transfer dana ke LSM / penghian...,amerika siap transfer dana ke lsm penghianat b...,
307,"Mulai Amerika ngacau, ingat dulu waktu indones...",mulai amerika ngacau ingat dulu waktu indonesi...,
90,Jangan dengarkan rakyat yang bilang indo blum ...,jangan dengarkan rakyat yang bilang indo blum ...,
265,"Mau disebut negara maju tapi kenyataan,,,,,,GA...",mau disebut negara maju tapi kenyataangaji upa...,
150,Pakai nuklir dari rusia mantap,pakai nuklir dari rusia mantap,

In [ ]:
sample_label.to_csv("sample_labeling_300.csv", index=False, encoding="utf-8-sig")

In [ ]:
from google.colab import files
files.download("sample_labeling_300.csv")